# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40b2eb0091b3821b93f0286444baaeea268fa29196c79063595c8cb530592583e3d876041d4a9ffd034408b4b4164faf713ad99e144b9db71a0cb63f8e4470da

test:
  secret_key_base: 22a35057766e0a75e01812305c09a645d45ac68c68ccd03328976b3b1505611c7895eb11f82623f94714d2d677ce4f9676b2a62874203c0df313f2d71420c2cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
